name: Deploy HTML to Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > DiGi_Salesta.pem
          chmod 600 DiGi_Salesta.pem

      - name: Debug SSH Connection
        run: ssh -v -o StrictHostKeyChecking=no -i DiGi_Salesta.pem ec2-user@54.95.36.216 "echo 'SSH Connected Successfully'"

      - name: Deploy to EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no -i DiGi_Salesta.pem ec2-user@54.95.36.216 << 'EOF'
            sudo rm -rf /var/www/html/*
            git clone https://github.com/keramot-it/keramot-project-repo.git /var/www/html/
            sudo systemctl restart nginx
          EOF
